FROM nginx:1.25-alpine

# Удаляем дефолтный конфиг
RUN rm /etc/nginx/conf.d/default.conf

# Копируем кастомный Nginx конфиг
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Копируем статические файлы фронтенда
COPY frontend/ /usr/share/nginx/html/

# Исправляем права доступа (некоторые файлы могут иметь 600)
RUN find /usr/share/nginx/html -type f -exec chmod 644 {} + && \
    find /usr/share/nginx/html -type d -exec chmod 755 {} +

EXPOSE 80
